### ISSUE TITLE
Terminar traducciones del Contenido Dexterity folder

### ISSUE THREAD

**Issue by soullessdead** [CanaimaGNULinux/buildout.web.canaimagnulinux#17]
Falta por traducciones

**Comment by macagua** [comment]
@soullessdead este tipo de contenido es de prueba y no se va a utilizar, por los momentos solo se deshabilitara que sea agregable desde la herramienta del ZMI portal_types > Dexterity folder y desmarco la casilla Implicitly addable? y hago clic en el botón Save
