### ISSUE TITLE
Portada terminar traducciones

### ISSUE THREAD

**Issue by soullessdead** [CanaimaGNULinux/buildout.web.canaimagnulinux#22]
![captura de pantalla de 2014-12-04 11 58 03](https://cloud.githubusercontent.com/assets/6645054/5301680/e2aa69fa-7bac-11e4-9498-9cf99648e439.png)

![captura de pantalla de 2014-12-04 11 59 14](https://cloud.githubusercontent.com/assets/6645054/5301697/0586237e-7bad-11e4-9ea4-cb1030b53707.png)

**Comment by macagua** [comment]
@soullessdead  la elección del layout se resuelve traduciendo los nombres de los layout predefinidos en el panel Registro de configuración, haga clic en *collective cover controlpanel ICoverSettings layouts* 

![captura de pantalla de 2015-06-06 14 26 26](https://cloud.githubusercontent.com/assets/185395/8021056/347d8124-0c5b-11e5-9151-f88c6b66849a.png)

![captura de pantalla de 2015-06-06 14 33 24](https://cloud.githubusercontent.com/assets/185395/8021057/362d5a62-0c5b-11e5-8835-4304b0e87027.png)

Entonces cierto esta incidencia como resuelta!
