### ISSUE TITLE
Multiples archivos terminar traducciones

### ISSUE THREAD

**Issue by soullessdead** [CanaimaGNULinux/buildout.web.canaimagnulinux#24]
Falta revisar las traducciones y el porque no las toma
![captura de pantalla de 2014-12-04 11 40 24](https://cloud.githubusercontent.com/assets/6645054/5301340/63f21024-7baa-11e4-9f43-0263a6ef8107.png)

**Comment by macagua** [comment]
@soullessdead resuelto con la actualizacion de la versión del paquete!
